#!/usr/bin/env python3
"""Generate foods-usda.js from USDA Data/foods_curated.csv.

The curated CSV is the source of truth — maintained by the R notebook
in USDA Data/. This script only does mechanical schema translation:
  CSV row → JS object with the shape FOODS_USDA expects.
"""
import csv
import json
import os
import sys

CSV  = os.path.join(os.path.dirname(__file__), 'USDA Data', 'foods_curated.csv')
OUT  = os.path.join(os.path.dirname(__file__), 'foods-usda.js')

# Default emoji per category — used when the CSV `emoji` field is blank.
EMOJI_DEFAULTS = {
    'Grains':           '🌾',
    'Legumes':          '🫘',
    'Vegetables':       '🥬',
    'Nuts':             '🥜',
    'Seeds':            '🌻',
    'Spreads':          '🥣',
    'Flours':           '🌾',
    'Protein Powders':  '💪',
    'Other':            '🟢',
}

def num(v, default=0):
    if v is None or v == '' or v == 'NA':
        return default
    try:
        return float(v)
    except ValueError:
        return default

def boolish(v):
    return str(v).strip().lower() in ('true', '1', 't', 'yes')

def main():
    rows = list(csv.DictReader(open(CSV)))
    print(f'read {len(rows)} curated rows from {CSV}', file=sys.stderr)

    out = []
    skipped = []
    for r in rows:
        cost_raw = r.get('cost_per_100g')
        if not cost_raw or cost_raw == 'NA':
            # Cost-free rows would be picked freely by the LP — exclude
            # from the eager set until we add a "browse without cost" mode.
            skipped.append((r['id'], 'no cost'))
            continue

        # Met+Cys → Met (FAO sulfur-amino-acid pool).
        met = num(r.get('Met_mg')) + num(r.get('Cys_mg'))
        # Phe+Tyr → Phe (FAO aromatic-amino-acid pool).
        # Prefer the precomputed Phe_Tyr_mg column; fall back to the sum.
        phe_tyr_raw = r.get('Phe_Tyr_mg')
        if phe_tyr_raw and phe_tyr_raw != 'NA':
            phe = num(phe_tyr_raw)
        else:
            phe = num(r.get('Phe_mg')) + num(r.get('Tyr_mg'))

        amino = {
            'His': round(num(r.get('His_mg'))),
            'Ile': round(num(r.get('Ile_mg'))),
            'Leu': round(num(r.get('Leu_mg'))),
            'Lys': round(num(r.get('Lys_mg'))),
            'Met': round(met),
            'Phe': round(phe),
            'Thr': round(num(r.get('Thr_mg'))),
            'Trp': round(num(r.get('Trp_mg'))),
            'Val': round(num(r.get('Val_mg'))),
        }
        if sum(amino.values()) == 0:
            skipped.append((r['id'], 'no amino data'))
            continue

        cat   = r.get('category') or 'Other'
        emoji = r.get('emoji') or EMOJI_DEFAULTS.get(cat, '🟢')
        svg   = (r.get('svg') or '').strip() or None

        food = {
            'id':      r['id'],
            'cat':     cat,
            'name':    r.get('display_name') or r['id'],
            'emoji':   emoji,
            **({'svg': svg} if svg else {}),
            'cost':    round(num(cost_raw), 4),
            'protein': round(num(r.get('protein_g')), 2),
            'fat':     round(num(r.get('fat_g')),     2),
            'carbs':   round(num(r.get('carbs_g')),   2),
            'fiber':   round(num(r.get('fiber_g')),   2),
            'kcal':    round(num(r.get('kcal'))),
            'fdc':     int(r['fdc_id']) if r.get('fdc_id') and r['fdc_id'] != 'NA' else None,
            'amino':   amino,
        }
        if r.get('form'):
            food['state'] = r['form']

        if not boolish(r.get('scalable', 'true')):
            food['scalable'] = False
            serving = r.get('serving_g')
            if serving and serving != 'NA':
                food['serving'] = round(num(serving))

        out.append(food)

    print(f'wrote {len(out)} foods, skipped {len(skipped)}', file=sys.stderr)
    for sid, why in skipped:
        print(f'  skip {sid}: {why}', file=sys.stderr)

    with open(OUT, 'w') as f:
        f.write('// AUTO-GENERATED by build_foods.py from USDA Data/foods_curated.csv.\n')
        f.write('// Amino acids: mg per 100 g of food. Met = Met+Cys, Phe = Phe+Tyr.\n')
        f.write('window.FOODS_USDA = ')
        json.dump(out, f, indent=2, ensure_ascii=False)
        f.write(';\n')
    print(f'wrote {OUT}', file=sys.stderr)

if __name__ == '__main__':
    main()
